### ISSUE TITLE
which switches will fit?

### ISSUE THREAD

**Issue by roy** [adereth/dactyl-keyboard#13]
I understand that you used gatheron switches in your current keyboards.
I'd like to put in mx brown switches, but I don't know if I need to use pcb or plate mounted switches.
Do you happen to know this?

**Comment by mathias** [comment]
I'm fairly certain that Gateron makes their switches the same size as Cherry MX switches.

Most DIY keyboards use plate-mounted switches: they "snap in" to a plate rather than get soldered onto a PCB. So for this keyboard, you'll need plate-mount Cherry MX switches.

**Comment by roy** [comment]
Awesome, thanks :)
