### ISSUE TITLE
Issue with stl in the /things/

### ISSUE THREAD

**Issue by oilydog** [adereth/dactyl-keyboard#15]
I uploaded the dactyl top right to a 3d printer website in Aus, and this is the quote. http://i.imgur.com/KPVQxwV.png
Im going to guess that _maybe_ that are not just doing the usual aussie overcharging.

**Comment by mathias** [comment]
Looks like the size is huge -- I'd check the units used and what they expect?

**Comment by adereth** [comment]
Yes, the units should be millimeters.  If that's already correct, I recommend using a different print shop 😄
