### ISSUE TITLE
Typo in README.org guide folder 

### ISSUE THREAD

**Issue by joe-warren** [adereth/dactyl-keyboard#38]
The readme in the guide folder has a handful of instances of TTRS that should read TRRS, this is confusing when shopping for parts.

**Comment by edkolev** [comment]
Why don't you submit a PR?

**Comment by joe-warren** [comment]
I've just submitted one, thanks

**Comment by edkolev** [comment]
Sure, no problem. You can also close this issue to reduce the work of the maintainer -- he'll spend time for dactyl instead of spending time on managing github issues
