### ISSUE TITLE
Incorrect pinout with the Teensy & MCP diagram in guide/circuit-diagram.png

### ISSUE THREAD

**Issue by raychengy** [adereth/dactyl-keyboard#57]
Based on the ErgoDox EZ [schematics](https://github.com/ErgoDox-EZ/docs/blob/master/ErgoDox%20EZ%20Schematic.pdf), pin `INTA` on the MCP23018 is not used. I think there is a simple mistake on the [guide/circuit-diagram.png](https://github.com/adereth/dactyl-keyboard/blob/master/guide/circuit-diagram.png) file. Could you tell me what program was used to make this diagram? Col-5 to Col-0 needs to be shifted up a input on the MCP23018 schematic.

![screen shot 2018-04-01 at 5 43 20 pm](https://user-images.githubusercontent.com/16471877/38177889-a4cefb5a-35d5-11e8-9cae-11f648d0e753.png)

**Comment by Mese96** [comment]
These pull request would fix this:
https://github.com/adereth/dactyl-keyboard/pull/51

**Comment by raychengy** [comment]
Awesome! I'll close out this issue.

**Comment by nomath4u** [comment]
This never got pulled in.

**Comment by Marcus-Zhu** [comment]
Please consider pulling this fix.

**Comment by nomath4u** [comment]
Just started making my second one and made the same mistake again 😭
