### ISSUE TITLE
Sizes of thumb cluster LightCycle's keycaps ?

### ISSUE THREAD

**Issue by manolodeinternet** [adereth/dactyl-keyboard#59]
I'm going to make a Dactyl LightCycle with Matias switches and I don't find anywhere what thumb cluster keycaps sizes are.  And there are very few offers for buying ALPS keycaps on the web.  

Does anyone can tell me if they are 2u, 1.5u, 1.25u, or something else ?  I want to find them and order them before build the keyboard.

**Comment by jaredjennings** [comment]
```
(defn thumb-layout [shape]
  (union
   (thumb-place 0 -1/2 (union shape (extended-plates 2)))

   (thumb-place 1 7/8 (union shape (extended-plates 1.25)))
   (thumb-place 1 -5/8 (union shape (extended-plates 1.75)))

   (thumb-place 2 -3/4 (union shape (extended-plates 1.5)))
   (thumb-place 2 3/4 (union shape (extended-plates 1.5)))
   ))
```

This says to me that you have one 2u key, one 1.25u key, one 1.75u key, and two 1.5u keys. After an image search, I'm confident I've read the code above correctly.

Good luck with the Alps keycaps. I'd like to see how things turn out for you! Maybe post on Geekhack or r/mechanicalkeyboards?

**Comment by manolodeinternet** [comment]
Thank you @jaredjennings !
I'll post on Geekhack or r/mechanicalkeyboards when it was finished.

Thanks, dude !!!
