### ISSUE TITLE
Wiritng Diode parts

### ISSUE THREAD

**Issue by Deiru2k** [adereth/dactyl-keyboard#67]
Hi! I never ever built a keyboard in my whole life, and this project grabbed my attention (mainly because I want kinesis with the split of ergodox on top). I managed to assemble pretty much everything except for the diodes. The guide states that Adereth got his diodes for free, but he never stated which diodes those are.

I have opened my local hardware store's page and noticed that there are tons of different kinds of diodes so natural question here is what kind of diode do I need for this and what params should it posess?

**Comment by impaktor** [comment]
1N4148

Check out these sites, they have good build logs (slightly different geometry, and use arduino instead of teensy, but "same-same")
https://github.com/20lives/Dactyl-Manuform
https://github.com/abstracthat/dactyl-manuform

**Comment by Deiru2k** [comment]
That was blazingly fast!
Yeah, I guess it doesn't matter what shape your board is when it comes to wiring keys.

Many thanks for this! Maybe the guide needs a PR with this.

**Comment by impaktor** [comment]
Feel free to close this issue, I suppose.

**Comment by Deiru2k** [comment]
A bit late, but yes, marking this as closed.
